# Generated by Django 5.2.15 on 2026-07-04 03:18

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camp', '0002_taxaddon_taxoverride_taxtier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('requires_review', 'Requires review')], default='created', max_length=30)),
                ('stripe_mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], max_length=10)),
                ('tax_amount_cents', models.PositiveIntegerField()),
                ('add_on_amount_cents', models.PositiveIntegerField(default=0)),
                ('total_amount_cents', models.PositiveIntegerField()),
                ('tax_tier_name_snapshot', models.CharField(max_length=120)),
                ('tax_tier_minimum_cents_snapshot', models.PositiveIntegerField()),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('checkout_created_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='camp.campyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=120)),
                ('amount_cents_snapshot', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='payments.payment')),
                ('tax_add_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camp.taxaddon')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('event_type', models.CharField(max_length=120)),
                ('stripe_mode', models.CharField(blank=True, max_length=10)),
                ('stripe_event_id', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('redacted_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'camp_year'], name='payments_pa_user_id_cb1448_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_mode', 'status'], name='payments_pa_stripe__3dc334_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'paid')), fields=('user', 'camp_year'), name='unique_paid_payment_user_year'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount_cents', django.db.models.expressions.CombinedExpression(models.F('tax_amount_cents'), '+', models.F('add_on_amount_cents')))), name='payment_total_matches_parts'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='payment_paid_requires_paid_at'),
        ),
    ]
