# Generated by Django 5.2.15 on 2026-07-04 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_add_ons', to='camp.campyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_add_ons', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tax_add_ons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'amount_cents', 'name'],
                'indexes': [models.Index(fields=['camp_year', 'start_date', 'expiration_date'], name='camp_taxadd_camp_ye_2667b9_idx'), models.Index(fields=['camp_year', 'display_order'], name='camp_taxadd_camp_ye_1af8c5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expiration_date__gt', models.F('start_date'))), name='tax_add_on_expiration_after_start'), models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='tax_add_on_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='TaxOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('reduced_minimum', 'Reduced minimum'), ('waived', 'Waived')], max_length=30)),
                ('reduced_minimum_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_overrides', to='camp.campyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_overrides', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tax_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'camp_year'), name='unique_tax_override_user_year'), models.CheckConstraint(condition=models.Q(models.Q(('override_type', 'reduced_minimum'), ('reduced_minimum_amount_cents__isnull', False)), models.Q(('override_type', 'waived'), ('reduced_minimum_amount_cents__isnull', True)), _connector='OR'), name='tax_override_type_amount_consistent'), models.CheckConstraint(condition=models.Q(('reduced_minimum_amount_cents__isnull', True), ('reduced_minimum_amount_cents__gt', 0), _connector='OR'), name='tax_override_reduced_minimum_positive')],
            },
        ),
        migrations.CreateModel(
            name='TaxTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('minimum_amount_cents', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_tiers', to='camp.campyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_tiers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tax_tiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'minimum_amount_cents', 'name'],
                'indexes': [models.Index(fields=['camp_year', 'start_date', 'expiration_date'], name='camp_taxtie_camp_ye_193b91_idx'), models.Index(fields=['camp_year', 'display_order'], name='camp_taxtie_camp_ye_f7b8f1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expiration_date__gt', models.F('start_date'))), name='tax_tier_expiration_after_start'), models.CheckConstraint(condition=models.Q(('minimum_amount_cents__gt', 0)), name='tax_tier_minimum_amount_positive')],
            },
        ),
    ]
