# Generated by Django 5.2.15 on 2026-07-12 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_taxaddon_taxoverride_taxtier'),
        ('surveys', '0002_survey_redirect_after_submission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campyear',
            name='camp_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camp_years_as_camp_survey', to='surveys.survey'),
        ),
    ]
