# Generated by Django 5.2.15 on 2026-07-11 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description_markdown', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description_markdown', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('single_choice', 'Single choice'), ('multi_choice', 'Multiple choice')], max_length=30)),
                ('render_hint', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('date', 'Date'), ('radio', 'Radio buttons'), ('select', 'Select dropdown'), ('scale', 'Scale'), ('checkboxes', 'Checkboxes')], max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('allows_other', models.BooleanField(default=False)),
                ('other_label', models.CharField(blank=True, default='Other', max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.surveyquestion')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_conditions', to='surveys.surveyquestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='surveys.surveyquestion')),
                ('visible_if_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='surveys.surveychoice')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id_snapshot', models.PositiveBigIntegerField()),
                ('question_name_snapshot', models.CharField(max_length=250)),
                ('question_type_snapshot', models.CharField(max_length=30)),
                ('render_hint_snapshot', models.CharField(max_length=30)),
                ('value', models.TextField(default='[]')),
                ('choice_snapshot', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='surveys.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse')),
            ],
            options={
                'ordering': ['question_id_snapshot', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='surveyquestion',
            index=models.Index(fields=['survey', 'display_order'], name='surveys_sur_survey__d42f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='surveychoice',
            index=models.Index(fields=['question', 'display_order'], name='surveys_sur_questio_32f8bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyquestioncondition',
            constraint=models.UniqueConstraint(fields=('question', 'depends_on_question', 'visible_if_choice'), name='unique_survey_question_condition_choice'),
        ),
        migrations.AddConstraint(
            model_name='surveyquestioncondition',
            constraint=models.CheckConstraint(condition=models.Q(('question_id', models.F('depends_on_question_id')), _negated=True), name='survey_question_condition_not_self'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('survey', 'user'), name='unique_survey_response_user'),
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('response', 'question'), name='unique_current_survey_answer_question'),
        ),
    ]
